services:
  app:
    build: .
    ports:
      - "8888:80"
      - "9900-9910:9900-9910"
    env_file:
      - .env
    environment:
      - GO2RTC_URL=http://127.0.0.1:1984
    depends_on:
      - go2rtc
    restart: unless-stopped
    network_mode: host

  go2rtc:
    image: alexxit/go2rtc
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml
    restart: unless-stopped
    network_mode: host
